version: '3'
services:
  gallery:
    container_name: gallery
    build:
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - postgres
      - minio
    restart: always
    networks:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .dev.env
    networks:
      - postgres
  minio:
    container_name: minio
    image: docker.io/bitnami/minio:2022
    env_file:
      - .dev.env
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9001:9001
    command: minio server --console-address ":9001" /data
    volumes:
      - 'minio_data:/data'
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .dev.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  minio_data:
    driver: local
